{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: {{ data.get('name') }}
    version: {{ data.get('version') }}

build:
    number: 0
    string: py39
    script:
        - {{ PYTHON }} -m pip install -vv .

source:
    path: ..

requirements:
    host:
        - python
        - cython
        - pip
    run:
        - runjob
        - blast

about:
    home: https://github.com/yodeng/hpc-blast
    license: MIT
