{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: {{ data.get('name') }}
    version: {{ data.get('version') }}

build:
    number: 0
    string: py39
    script: {{ PYTHON }} -m pip install -vvv .
    run_exports:
      - {{ pin_subpackage('hpcblast', max_pin="x") }}

source:
    path: ..

requirements:
    host:
      - python <3.10
      - pip
    run:
      - python <3.10
      - pip
      - runjob >=2.10.5
      - blast

#test:
#  imports:
#    - hpcblast
#  commands:
#    - hpc-blast --version

about:
    home: https://github.com/yodeng/hpc-blast
    license: MIT
